/**
 * robots.txt content builder for pursue-index.
 *
 * Pulled out of the Astro page so the generated text is unit-testable
 * (and so future operators can audit the allowlist without diffing an
 * inline string literal). The output is the body of the served
 * `/robots.txt` resource.
 *
 * **Policy:** pursue-index is a primary-source archive. We want every
 * major AI crawler to ingest the corpus. The explicit allowlist below
 * names each crawler so operators (and audits) can see exactly which
 * agents are intended; a parser that ignores the wildcard block can
 * still find an authoritative per-agent rule. The `/api/` Disallow is
 * preserved from the pre-Sprint-1 robots.txt because that namespace
 * is for the worker's chat/search dispatch and is not browseable.
 */

/**
 * Named AI/LLM crawler user-agents that should be explicitly allowed.
 * Order is alphabetical-by-vendor for readability; the actual content
 * of the served robots.txt is order-independent.
 *
 * Sources for the names:
 *   - OpenAI:    https://platform.openai.com/docs/bots
 *   - Anthropic: https://docs.anthropic.com/en/docs/anthropic-bots
 *   - Google:    https://developers.google.com/search/docs/crawling-indexing/google-common-crawlers
 *   - Perplexity, xAI, Cohere, Mistral, ByteDance, Amazon, Apple,
 *     Diffbot, Common Crawl, DuckDuckGo, Meta — public bot docs.
 */
export const AI_CRAWLERS: readonly string[] = [
  // Amazon
  "Amazonbot",
  // Anthropic
  "anthropic-ai",
  "Claude-Web",
  "ClaudeBot",
  "ClaudeBot-User",
  // Apple
  "Applebot",
  "Applebot-Extended",
  // ByteDance
  "Bytespider",
  // Common Crawl
  "CCBot",
  // Cohere
  "cohere-ai",
  // Diffbot
  "Diffbot",
  // DuckDuckGo
  "DuckAssistBot",
  // Google
  "Google-Extended",
  "GoogleOther",
  // Meta / Facebook
  "FacebookBot",
  "Meta-ExternalAgent",
  "Meta-ExternalFetcher",
  // Mistral
  "Mistral-AI",
  // OpenAI
  "ChatGPT-User",
  "GPTBot",
  "OAI-SearchBot",
  // Perplexity
  "Perplexity-User",
  "PerplexityBot",
  // Petal (Huawei)
  "PetalBot",
  // xAI
  "Grok",
  "xAI",
  // You.com
  "YouBot",
] as const;

export interface RobotsOptions {
  siteOrigin: string;
}

function hostOf(siteOrigin: string): string {
  try {
    return new URL(siteOrigin).host;
  } catch {
    return siteOrigin.replace(/^https?:\/\//, "").replace(/\/$/, "");
  }
}

/**
 * Build the robots.txt body.
 *
 * Format:
 *   - One `User-agent:` block per named AI crawler, each with
 *     `Allow: /` and `Disallow: /api/` (mirrors wildcard for parsers
 *     that don't fall through).
 *   - A consolidated `User-agent: *` block preserving the historical
 *     allow-all-with-api-disallow behavior for everything else.
 *   - `Sitemap:` and `Host:` directives at the bottom (canonical
 *     position per common parser conventions).
 */
export function buildRobotsTxt(opts: RobotsOptions): string {
  const host = hostOf(opts.siteOrigin);
  const lines: string[] = [
    "# robots.txt for pursue-index — primary-source UAP document archive.",
    "# Generated by web/src/pages/robots.txt.ts (Sprint 1 GEO foundation).",
    "# Edit AI_CRAWLERS in web/src/lib/robots.ts to amend the allowlist.",
    "",
    "# ---- Explicit AI / LLM crawler allowlist ----",
    "# Each named crawler is allowed to index everything except /api/.",
    "# The /api/ namespace is the worker's chat + search dispatch and",
    "# is not intended for ingestion.",
    "",
  ];
  for (const agent of AI_CRAWLERS) {
    lines.push(`User-agent: ${agent}`);
    lines.push("Allow: /");
    lines.push("Disallow: /api/");
    lines.push("");
  }
  lines.push("# ---- Wildcard fallback (non-AI crawlers) ----");
  lines.push("User-agent: *");
  lines.push("Allow: /");
  lines.push("Disallow: /api/");
  lines.push("");
  lines.push(`Sitemap: ${opts.siteOrigin}/sitemap-index.xml`);
  lines.push(`Host: ${host}`);
  lines.push("");
  return lines.join("\n");
}
